export const neetcode150 = [
  { title: "Contains Duplicate", platform: "LeetCode", difficulty: "Easy", tags: ["arrays", "hashing"], url: "https://leetcode.com/problems/contains-duplicate/" },
  { title: "Valid Anagram", platform: "LeetCode", difficulty: "Easy", tags: ["arrays", "hashing", "strings"], url: "https://leetcode.com/problems/valid-anagram/" },
  { title: "Two Sum", platform: "LeetCode", difficulty: "Easy", tags: ["arrays", "hashing"], url: "https://leetcode.com/problems/two-sum/" },
  { title: "Group Anagrams", platform: "LeetCode", difficulty: "Medium", tags: ["arrays", "hashing", "strings"], url: "https://leetcode.com/problems/group-anagrams/" },
  { title: "Top K Frequent Elements", platform: "LeetCode", difficulty: "Medium", tags: ["arrays", "hashing"], url: "https://leetcode.com/problems/top-k-frequent-elements/" },
  { title: "Product of Array Except Self", platform: "LeetCode", difficulty: "Medium", tags: ["arrays", "math"], url: "https://leetcode.com/problems/product-of-array-except-self/" },
  { title: "Valid Sudoku", platform: "LeetCode", difficulty: "Medium", tags: ["arrays", "hashing"], url: "https://leetcode.com/problems/valid-sudoku/" },
  { title: "Longest Consecutive Sequence", platform: "LeetCode", difficulty: "Medium", tags: ["arrays", "hashing"], url: "https://leetcode.com/problems/longest-consecutive-sequence/" },
  { title: "Valid Palindrome", platform: "LeetCode", difficulty: "Easy", tags: ["two pointers", "strings"], url: "https://leetcode.com/problems/valid-palindrome/" },
  { title: "Two Sum II - Input Array Is Sorted", platform: "LeetCode", difficulty: "Medium", tags: ["two pointers", "arrays"], url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/" },
  { title: "3Sum", platform: "LeetCode", difficulty: "Medium", tags: ["two pointers", "arrays"], url: "https://leetcode.com/problems/3sum/" },
  { title: "Container With Most Water", platform: "LeetCode", difficulty: "Medium", tags: ["two pointers", "arrays"], url: "https://leetcode.com/problems/container-with-most-water/" },
  { title: "Trapping Rain Water", platform: "LeetCode", difficulty: "Hard", tags: ["two pointers", "arrays"], url: "https://leetcode.com/problems/trapping-rain-water/" },
  { title: "Best Time to Buy and Sell Stock", platform: "LeetCode", difficulty: "Easy", tags: ["sliding window", "arrays"], url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
  { title: "Longest Substring Without Repeating Characters", platform: "LeetCode", difficulty: "Medium", tags: ["sliding window", "strings", "hashing"], url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
  { title: "Longest Repeating Character Replacement", platform: "LeetCode", difficulty: "Medium", tags: ["sliding window", "strings", "hashing"], url: "https://leetcode.com/problems/longest-repeating-character-replacement/" },
  { title: "Permutation in String", platform: "LeetCode", difficulty: "Medium", tags: ["sliding window", "strings", "hashing"], url: "https://leetcode.com/problems/permutation-in-string/" },
  { title: "Minimum Window Substring", platform: "LeetCode", difficulty: "Hard", tags: ["sliding window", "strings", "hashing"], url: "https://leetcode.com/problems/minimum-window-substring/" },
  { title: "Sliding Window Maximum", platform: "LeetCode", difficulty: "Hard", tags: ["sliding window", "arrays", "queue"], url: "https://leetcode.com/problems/sliding-window-maximum/" },
  { title: "Valid Parentheses", platform: "LeetCode", difficulty: "Easy", tags: ["stack", "strings"], url: "https://leetcode.com/problems/valid-parentheses/" },
  { title: "Min Stack", platform: "LeetCode", difficulty: "Medium", tags: ["stack"], url: "https://leetcode.com/problems/min-stack/" },
  { title: "Evaluate Reverse Polish Notation", platform: "LeetCode", difficulty: "Medium", tags: ["stack", "math"], url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/" },
  { title: "Generate Parentheses", platform: "LeetCode", difficulty: "Medium", tags: ["stack", "strings"], url: "https://leetcode.com/problems/generate-parentheses/" },
  { title: "Daily Temperatures", platform: "LeetCode", difficulty: "Medium", tags: ["stack", "arrays"], url: "https://leetcode.com/problems/daily-temperatures/" },
  { title: "Car Fleet", platform: "LeetCode", difficulty: "Medium", tags: ["stack", "arrays"], url: "https://leetcode.com/problems/car-fleet/" },
  { title: "Largest Rectangle in Histogram", platform: "LeetCode", difficulty: "Hard", tags: ["stack", "arrays"], url: "https://leetcode.com/problems/largest-rectangle-in-histogram/" },
  { title: "Binary Search", platform: "LeetCode", difficulty: "Easy", tags: ["binary search", "arrays"], url: "https://leetcode.com/problems/binary-search/" },
  { title: "Search a 2D Matrix", platform: "LeetCode", difficulty: "Medium", tags: ["binary search", "arrays"], url: "https://leetcode.com/problems/search-a-2d-matrix/" },
  { title: "Koko Eating Bananas", platform: "LeetCode", difficulty: "Medium", tags: ["binary search", "arrays", "math"], url: "https://leetcode.com/problems/koko-eating-bananas/" },
  { title: "Find Minimum in Rotated Sorted Array", platform: "LeetCode", difficulty: "Medium", tags: ["binary search", "arrays"], url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/" },
  { title: "Search in Rotated Sorted Array", platform: "LeetCode", difficulty: "Medium", tags: ["binary search", "arrays"], url: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
  { title: "Time Based Key-Value Store", platform: "LeetCode", difficulty: "Medium", tags: ["binary search", "hashing"], url: "https://leetcode.com/problems/time-based-key-value-store/" },
  { title: "Median of Two Sorted Arrays", platform: "LeetCode", difficulty: "Hard", tags: ["binary search", "arrays"], url: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
  { title: "Reverse Linked List", platform: "LeetCode", difficulty: "Easy", tags: ["linked list"], url: "https://leetcode.com/problems/reverse-linked-list/" },
  { title: "Merge Two Sorted Lists", platform: "LeetCode", difficulty: "Easy", tags: ["linked list"], url: "https://leetcode.com/problems/merge-two-sorted-lists/" },
  { title: "Reorder List", platform: "LeetCode", difficulty: "Medium", tags: ["linked list"], url: "https://leetcode.com/problems/reorder-list/" },
  { title: "Remove Nth Node From End of List", platform: "LeetCode", difficulty: "Medium", tags: ["linked list"], url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
  { title: "Copy List with Random Pointer", platform: "LeetCode", difficulty: "Medium", tags: ["linked list", "hashing"], url: "https://leetcode.com/problems/copy-list-with-random-pointer/" },
  { title: "Add Two Numbers", platform: "LeetCode", difficulty: "Medium", tags: ["linked list", "math"], url: "https://leetcode.com/problems/add-two-numbers/" },
  { title: "Linked List Cycle", platform: "LeetCode", difficulty: "Easy", tags: ["linked list", "two pointers"], url: "https://leetcode.com/problems/linked-list-cycle/" },
  { title: "Find the Duplicate Number", platform: "LeetCode", difficulty: "Medium", tags: ["linked list", "two pointers"], url: "https://leetcode.com/problems/find-the-duplicate-number/" },
  { title: "LRU Cache", platform: "LeetCode", difficulty: "Medium", tags: ["linked list", "hashing"], url: "https://leetcode.com/problems/lru-cache/" },
  { title: "Merge k Sorted Lists", platform: "LeetCode", difficulty: "Hard", tags: ["linked list"], url: "https://leetcode.com/problems/merge-k-sorted-lists/" },
  { title: "Reverse Nodes in k-Group", platform: "LeetCode", difficulty: "Hard", tags: ["linked list"], url: "https://leetcode.com/problems/reverse-nodes-in-k-group/" },
  { title: "Invert Binary Tree", platform: "LeetCode", difficulty: "Easy", tags: ["trees"], url: "https://leetcode.com/problems/invert-binary-tree/" },
  { title: "Maximum Depth of Binary Tree", platform: "LeetCode", difficulty: "Easy", tags: ["trees"], url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
  { title: "Diameter of Binary Tree", platform: "LeetCode", difficulty: "Easy", tags: ["trees"], url: "https://leetcode.com/problems/diameter-of-binary-tree/" },
  { title: "Balanced Binary Tree", platform: "LeetCode", difficulty: "Easy", tags: ["trees"], url: "https://leetcode.com/problems/balanced-binary-tree/" },
  { title: "Same Tree", platform: "LeetCode", difficulty: "Easy", tags: ["trees"], url: "https://leetcode.com/problems/same-tree/" },
  { title: "Subtree of Another Tree", platform: "LeetCode", difficulty: "Easy", tags: ["trees"], url: "https://leetcode.com/problems/subtree-of-another-tree/" },
  { title: "Lowest Common Ancestor of a Binary Search Tree", platform: "LeetCode", difficulty: "Medium", tags: ["trees"], url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/" },
  { title: "Binary Tree Level Order Traversal", platform: "LeetCode", difficulty: "Medium", tags: ["trees", "queue"], url: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
  { title: "Binary Tree Right Side View", platform: "LeetCode", difficulty: "Medium", tags: ["trees", "queue"], url: "https://leetcode.com/problems/binary-tree-right-side-view/" },
  { title: "Count Good Nodes in Binary Tree", platform: "LeetCode", difficulty: "Medium", tags: ["trees"], url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/" },
  { title: "Validate Binary Search Tree", platform: "LeetCode", difficulty: "Medium", tags: ["trees"], url: "https://leetcode.com/problems/validate-binary-search-tree/" },
  { title: "Kth Smallest Element in a BST", platform: "LeetCode", difficulty: "Medium", tags: ["trees"], url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
  { title: "Construct Binary Tree from Preorder and Inorder Traversal", platform: "LeetCode", difficulty: "Medium", tags: ["trees", "arrays"], url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/" },
  { title: "Binary Tree Maximum Path Sum", platform: "LeetCode", difficulty: "Hard", tags: ["trees"], url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/" },
  { title: "Serialize and Deserialize Binary Tree", platform: "LeetCode", difficulty: "Hard", tags: ["trees", "strings"], url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" }
].map((p, idx) => ({ ...p, id: `nc150_${idx}` }));

export const cp31 = [
  { title: "Halloumi Boxes", platform: "Codeforces", difficulty: "800", tags: ["arrays", "sorting"], url: "https://codeforces.com/problemset/problem/1903/A" },
  { title: "Line Trip", platform: "Codeforces", difficulty: "800", tags: ["arrays", "math"], url: "https://codeforces.com/problemset/problem/1901/A" },
  { title: "Cover in Water", platform: "Codeforces", difficulty: "800", tags: ["strings"], url: "https://codeforces.com/problemset/problem/1900/A" },
  { title: "Game with Integers", platform: "Codeforces", difficulty: "800", tags: ["math", "games"], url: "https://codeforces.com/problemset/problem/1899/A" },
  { title: "Jagged Swaps", platform: "Codeforces", difficulty: "800", tags: ["arrays", "sorting"], url: "https://codeforces.com/problemset/problem/1896/A" },
  { title: "Doremy's Paint 3", platform: "Codeforces", difficulty: "800", tags: ["arrays", "hashing"], url: "https://codeforces.com/problemset/problem/1890/A" },
  { title: "Don't Try to Count", platform: "Codeforces", difficulty: "800", tags: ["strings", "brute force"], url: "https://codeforces.com/problemset/problem/1881/A" },
  { title: "How Much Does Daytona Cost?", platform: "Codeforces", difficulty: "800", tags: ["arrays", "greedy"], url: "https://codeforces.com/problemset/problem/1878/A" },
  { title: "Goals of Victory", platform: "Codeforces", difficulty: "800", tags: ["math", "arrays"], url: "https://codeforces.com/problemset/problem/1877/A" },
  { title: "Target Practice", platform: "Codeforces", difficulty: "800", tags: ["implementation", "math"], url: "https://codeforces.com/problemset/problem/1873/C" },
  { title: "Ambitious Kid", platform: "Codeforces", difficulty: "800", tags: ["math"], url: "https://codeforces.com/problemset/problem/1866/A" },
  { title: "Sequence Game", platform: "Codeforces", difficulty: "800", tags: ["arrays", "greedy"], url: "https://codeforces.com/problemset/problem/1862/B" },
  { title: "United We Stand", platform: "Codeforces", difficulty: "800", tags: ["math", "arrays"], url: "https://codeforces.com/problemset/problem/1859/A" },
  { title: "Buttons", platform: "Codeforces", difficulty: "800", tags: ["math", "games"], url: "https://codeforces.com/problemset/problem/1858/A" },
  { title: "Array Coloring", platform: "Codeforces", difficulty: "800", tags: ["math"], url: "https://codeforces.com/problemset/problem/1857/A" },
  { title: "Desorting", platform: "Codeforces", difficulty: "800", tags: ["math", "arrays"], url: "https://codeforces.com/problemset/problem/1853/A" },
  { title: "Dalton the Teacher", platform: "Codeforces", difficulty: "800", tags: ["math", "greedy"], url: "https://codeforces.com/problemset/problem/1855/A" },
  { title: "Grasshopper on a Line", platform: "Codeforces", difficulty: "800", tags: ["math"], url: "https://codeforces.com/problemset/problem/1837/A" },
  { title: "Twin Permutations", platform: "Codeforces", difficulty: "800", tags: ["math", "arrays"], url: "https://codeforces.com/problemset/problem/1831/A" },
  { title: "Blank Space", platform: "Codeforces", difficulty: "800", tags: ["arrays"], url: "https://codeforces.com/problemset/problem/1829/B" },
  { title: "Coins", platform: "Codeforces", difficulty: "800", tags: ["math"], url: "https://codeforces.com/problemset/problem/1814/A" },
  { title: "Walking Master", platform: "Codeforces", difficulty: "800", tags: ["math", "geometry"], url: "https://codeforces.com/problemset/problem/1806/A" },
  { title: "We Need the Zero", platform: "Codeforces", difficulty: "800", tags: ["bitmasks", "math"], url: "https://codeforces.com/problemset/problem/1805/A" },
  { title: "Prepend and Append", platform: "Codeforces", difficulty: "800", tags: ["two pointers", "strings"], url: "https://codeforces.com/problemset/problem/1791/C" },
  { title: "Extremely Round", platform: "Codeforces", difficulty: "800", tags: ["brute force", "math"], url: "https://codeforces.com/problemset/problem/1766/A" },
  { title: "Make it Beautiful", platform: "Codeforces", difficulty: "900", tags: ["math", "constructive"], url: "https://codeforces.com/problemset/problem/1783/A" },
  { title: "Everybody Likes Good Arrays!", platform: "Codeforces", difficulty: "900", tags: ["math", "arrays"], url: "https://codeforces.com/problemset/problem/1777/A" },
  { title: "One and Two", platform: "Codeforces", difficulty: "900", tags: ["brute force", "math"], url: "https://codeforces.com/problemset/problem/1788/A" },
  { title: "Not Dividing", platform: "Codeforces", difficulty: "900", tags: ["math", "constructive"], url: "https://codeforces.com/problemset/problem/1794/B" },
  { title: "Bad Boy", platform: "Codeforces", difficulty: "900", tags: ["math", "constructive"], url: "https://codeforces.com/problemset/problem/1537/B" },
  { title: "Olya and Game with Arrays", platform: "Codeforces", difficulty: "1000", tags: ["greedy", "arrays"], url: "https://codeforces.com/problemset/problem/1859/B" },
  { title: "Monsters", platform: "Codeforces", difficulty: "1000", tags: ["greedy", "math"], url: "https://codeforces.com/problemset/problem/1849/B" },
  { title: "Luke is a Foodie", platform: "Codeforces", difficulty: "1000", tags: ["greedy", "math"], url: "https://codeforces.com/problemset/problem/1704/B" },
  { title: "Shoe Shuffling", platform: "Codeforces", difficulty: "1000", tags: ["greedy", "constructive"], url: "https://codeforces.com/problemset/problem/1691/B" },
  { title: "Roof Construction", platform: "Codeforces", difficulty: "1000", tags: ["constructive", "bitmasks"], url: "https://codeforces.com/problemset/problem/1632/B" },
  { title: "Divan and a New Project", platform: "Codeforces", difficulty: "1000", tags: ["greedy", "sorting"], url: "https://codeforces.com/problemset/problem/1614/B" },
  { title: "Luntik and Subsequences", platform: "Codeforces", difficulty: "1000", tags: ["math", "combinatorics"], url: "https://codeforces.com/problemset/problem/1582/B" },
  { title: "Yarik and Array", platform: "Codeforces", difficulty: "1100", tags: ["arrays", "DP"], url: "https://codeforces.com/problemset/problem/1899/C" },
  { title: "Deja Vu", platform: "Codeforces", difficulty: "1100", tags: ["arrays", "math"], url: "https://codeforces.com/problemset/problem/1891/B" },
  { title: "250 Thousand Tons of TNT", platform: "Codeforces", difficulty: "1100", tags: ["math", "number theory"], url: "https://codeforces.com/problemset/problem/1899/B" },
  { title: "Copil Copac Draws Trees", platform: "Codeforces", difficulty: "1100", tags: ["trees", "graphs"], url: "https://codeforces.com/problemset/problem/1830/A" },
  { title: "Li Hua and Pattern", platform: "Codeforces", difficulty: "1100", tags: ["constructive", "greedy"], url: "https://codeforces.com/problemset/problem/1797/B" },
  { title: "JoJo's Incredible Adventures", platform: "Codeforces", difficulty: "1100", tags: ["strings", "math"], url: "https://codeforces.com/problemset/problem/1820/B" },
  { title: "Sort the Subarray", platform: "Codeforces", difficulty: "1100", tags: ["arrays", "two pointers"], url: "https://codeforces.com/problemset/problem/1821/B" },
  { title: "Vika and the Bridge", platform: "Codeforces", difficulty: "1200", tags: ["greedy", "math"], url: "https://codeforces.com/problemset/problem/1848/B" },
  { title: "Contrast Value", platform: "Codeforces", difficulty: "1200", tags: ["arrays", "greedy"], url: "https://codeforces.com/problemset/problem/1832/C" },
  { title: "Dora and Search", platform: "Codeforces", difficulty: "1200", tags: ["two pointers", "arrays"], url: "https://codeforces.com/problemset/problem/1793/C" },
  { title: "Matryoshkas", platform: "Codeforces", difficulty: "1200", tags: ["greedy", "hashing"], url: "https://codeforces.com/problemset/problem/1790/D" },
  { title: "Scoring Subsequences", platform: "Codeforces", difficulty: "1200", tags: ["two pointers", "math"], url: "https://codeforces.com/problemset/problem/1794/C" },
  { title: "Same Count One", platform: "Codeforces", difficulty: "1200", tags: ["constructive", "math"], url: "https://codeforces.com/problemset/problem/1774/C" },
  { title: "Friends and the Restaurant", platform: "Codeforces", difficulty: "1200", tags: ["greedy", "two pointers"], url: "https://codeforces.com/problemset/problem/1729/D" },
  { title: "Find and Replace", platform: "Codeforces", difficulty: "1300", tags: ["strings", "hashing"], url: "https://codeforces.com/problemset/problem/1810/C" },
  { title: "Prefix and Suffix Array", platform: "Codeforces", difficulty: "1300", tags: ["strings", "sorting"], url: "https://codeforces.com/problemset/problem/1795/C" },
  { title: "Tear It Apart", platform: "Codeforces", difficulty: "1300", tags: ["strings", "brute force"], url: "https://codeforces.com/problemset/problem/1821/C" },
  { title: "Make It Alternating", platform: "Codeforces", difficulty: "1300", tags: ["combinatorics", "greedy"], url: "https://codeforces.com/problemset/problem/1879/C" },
  { title: "Strong Vertices", platform: "Codeforces", difficulty: "1300", tags: ["graphs", "math"], url: "https://codeforces.com/problemset/problem/1857/D" },
  { title: "Jumping Through Segments", platform: "Codeforces", difficulty: "1400", tags: ["binary search", "greedy"], url: "https://codeforces.com/problemset/problem/1907/D" },
  { title: "Grouping Increases", platform: "Codeforces", difficulty: "1400", tags: ["greedy", "data structures"], url: "https://codeforces.com/problemset/problem/1915/E" },
  { title: "Quests", platform: "Codeforces", difficulty: "1400", tags: ["greedy", "math"], url: "https://codeforces.com/problemset/problem/1914/C" },
  { title: "Mathematical Problem", platform: "Codeforces", difficulty: "1400", tags: ["math", "constructive"], url: "https://codeforces.com/problemset/problem/1902/C" },
  { title: "Dance Lessons", platform: "Codeforces", difficulty: "1400", tags: ["data structures", "greedy"], url: "https://codeforces.com/problemset/problem/1899/D" },
  { title: "Data Structures Fan", platform: "Codeforces", difficulty: "1500", tags: ["bitmasks", "data structures"], url: "https://codeforces.com/problemset/problem/1872/E" },
  { title: "Smilo and Monsters", platform: "Codeforces", difficulty: "1500", tags: ["greedy", "sorting"], url: "https://codeforces.com/problemset/problem/1891/C" },
  { title: "Block Sequence", platform: "Codeforces", difficulty: "1500", tags: ["DP", "data structures"], url: "https://codeforces.com/problemset/problem/1881/E" },
  { title: "The Morning Star", platform: "Codeforces", difficulty: "1500", tags: ["math", "geometry"], url: "https://codeforces.com/problemset/problem/1850/H" },
  { title: "Little Girl and Maximum Sum", platform: "Codeforces", difficulty: "1500", tags: ["greedy", "data structures"], url: "https://codeforces.com/problemset/problem/276/C" },
  { title: "Bicycles", platform: "Codeforces", difficulty: "1600", tags: ["graphs", "shortest paths"], url: "https://codeforces.com/problemset/problem/1915/G" },
  { title: "Earning on Bets", platform: "Codeforces", difficulty: "1600", tags: ["math", "number theory"], url: "https://codeforces.com/problemset/problem/1902/D" },
  { title: "Prefix Purchase", platform: "Codeforces", difficulty: "1600", tags: ["greedy", "DP"], url: "https://codeforces.com/problemset/problem/1901/C" },
  { title: "Yet Another Monster Fight", platform: "Codeforces", difficulty: "1600", tags: ["binary search", "greedy"], url: "https://codeforces.com/problemset/problem/1890/D" },
  { title: "Good Subarrays", platform: "Codeforces", difficulty: "1600", tags: ["math", "data structures"], url: "https://codeforces.com/problemset/problem/1398/C" },
  { title: "Sorting By Multiplication", platform: "Codeforces", difficulty: "1700", tags: ["DP", "greedy"], url: "https://codeforces.com/problemset/problem/1891/F" },
  { title: "Mad City", platform: "Codeforces", difficulty: "1700", tags: ["graphs", "dfs and similar"], url: "https://codeforces.com/problemset/problem/1873/F" },
  { title: "Friendly Spiders", platform: "Codeforces", difficulty: "1700", tags: ["graphs", "number theory"], url: "https://codeforces.com/problemset/problem/1774/E" },
  { title: "Coloring", platform: "Codeforces", difficulty: "1700", tags: ["combinatorics", "math"], url: "https://codeforces.com/problemset/problem/1774/D" },
  { title: "Equalize the Array", platform: "Codeforces", difficulty: "1800", tags: ["data structures", "greedy"], url: "https://codeforces.com/problemset/problem/1490/F" },
  { title: "Maximum Distributed Tree", platform: "Codeforces", difficulty: "1800", tags: ["trees", "greedy"], url: "https://codeforces.com/problemset/problem/1401/D" },
  { title: "Secret Passwords", platform: "Codeforces", difficulty: "1800", tags: ["graphs", "dsu"], url: "https://codeforces.com/problemset/problem/1263/D" },
  { title: "Xenia and Bit Operations", platform: "Codeforces", difficulty: "1800", tags: ["trees", "data structures"], url: "https://codeforces.com/problemset/problem/339/D" }
].map((p, idx) => ({ ...p, id: `cp31_${idx}` }));

export const allProblems = [...neetcode150, ...cp31];
